// words.js
const commonWords = [
  "the", "be", "of", "and", "a", "to", "in", "he", "have", "it", "that", "for", "they", "I", "with",
  "as", "not", "on", "she", "at", "by", "this", "we", "you", "do", "but", "from", "or", "which",
  "one", "would", "all", "will", "there", "say", "who", "make", "when", "can", "more", "if", "no",
  "man", "out", "other", "so", "what", "time", "up", "go", "about", "than", "into", "could",
  "state", "only", "new", "year", "some", "take", "come", "these", "know", "see", "use", "get",
  "like", "then", "first", "any", "work", "now", "may", "such", "give", "over", "think", "most",
  "even", "find", "day", "also", "after", "way", "many", "must", "look", "before", "great",
  "back", "through", "long", "where", "much", "should", "well", "people", "down", "own", "just",
  "because", "good", "each", "those", "feel", "seem", "how", "high", "too", "place", "little",
  "world", "very", "still", "nation", "hand", "old", "life", "tell", "write", "become", "here",
  "show", "house", "both", "between", "need", "mean", "call", "develop", "under", "last",
  "right", "move", "thing", "general", "school", "never", "same", "another", "begin", "while",
  "number", "part", "turn", "real", "leave", "might", "want", "point", "form", "off", "child",
  "few", "small", "since", "against", "ask", "late", "home", "interest", "large", "person",
  "end", "open", "public", "follow", "during", "present", "without", "again", "hold", "govern",
  "around", "possible", "head", "consider", "word", "program", "problem", "however", "lead",
  "system", "set", "order", "eye", "plan", "run", "keep", "face", "fact", "group", "play",
  "stand", "increase", "early", "course", "change", "help", "line",
  
  // Additional common words
  "water", "been", "call", "oil", "its", "now", "find", "long", "down", "day", "did", "get", 
  "come", "made", "may", "part", "over", "new", "sound", "take", "only", "little", "work", 
  "know", "place", "year", "live", "me", "back", "give", "most", "very", "after", "thing", 
  "our", "just", "name", "good", "sentence", "man", "think", "say", "great", "where", "help", 
  "through", "much", "before", "line", "right", "too", "mean", "old", "any", "same", "tell", 
  "boy", "follow", "came", "want", "show", "also", "around", "form", "three", "small", "set", 
  "put", "end", "does", "another", "well", "large", "must", "big", "even", "such", "because", 
  "turn", "here", "why", "ask", "went", "men", "read", "need", "land", "different", "home", 
  "us", "move", "try", "kind", "hand", "picture", "again", "change", "off", "play", "spell", 
  "air", "away", "animal", "house", "point", "page", "letter", "mother", "answer", "found", 
  "study", "still", "learn", "should", "America", "world", "high", "every", "near", "add", 
  "food", "between", "own", "below", "country", "plant", "last", "school", "father", "keep", 
  "tree", "never", "start", "city", "earth", "eye", "light", "thought", "head", "under", 
  "story", "saw", "left", "don't", "few", "while", "along", "might", "close", "something", 
  "seem", "next", "hard", "open", "example", "begin", "life", "always", "those", "both", 
  "paper", "together", "got", "group", "often", "run", "important", "until", "children", 
  "side", "feet", "car", "mile", "night", "walk", "white", "sea", "began", "grow", "took", 
  "river", "four", "carry", "state", "once", "book", "hear", "stop", "without", "second", 
  "later", "miss", "idea", "enough", "eat", "face", "watch", "far", "Indian", "really", 
  "almost", "let", "above", "girl", "sometimes", "mountain", "cut", "young", "talk", "soon", 
  "list", "song", "being", "leave", "family", "it's", "body", "music", "color", "stand", 
  "sun", "question", "fish", "area", "mark", "dog", "horse", "birds", "problem", "complete", 
  "room", "knew", "since", "ever", "piece", "told", "usually", "didn't", "friends", "easy", 
  "heard", "order", "red", "door", "sure", "become", "top", "ship", "across", "today", 
  "during", "short", "better", "best", "low", "hour", "true", "hundred", "five", "remember", 
  "step", "early", "hold", "west", "ground", "interest", "reach", "fast", "verb", "sing", 
  "listen", "six", "table", "travel", "less", "morning", "ten", "simple", "several", "vowel", 
  "toward", "war", "lay", "against", "pattern", "slow", "center", "love", "person", "money", 
  "serve", "appear", "road", "map", "rain", "rule", "govern", "pull", "cold", "notice", 
  "voice", "unit", "power", "town", "fine", "certain", "fly", "fall", "lead", "cry", "dark", 
  "machine", "note", "wait", "plan", "figure", "star", "box", "noun", "field", "rest", 
  "correct", "able", "pound", "done", "beauty", "drive", "stood", "contain", "front", 
  "teach", "week", "final", "gave", "green", "oh", "quick", "develop", "ocean", "warm", 
  "free", "minute", "strong", "special", "mind", "behind", "clear", "tail", "produce", 
  "fact", "space", "heard", "best", "hour", "better", "true", "during", "hundred", "five", 
  "remember", "step", "early", "hold", "west", "ground", "interest", "reach", "fast", "verb"
];